
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getShow() : Promise<Result<Show, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_show") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openShowfile(filePath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_showfile", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWingChannelInfo(channel: number) : Promise<Result<WingChannelInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_wing_channel_info", { channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addActor(channel: WingChannelId, name: string, color: WingColor | null) : Promise<Result<ActorId, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_actor", { channel, name, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
actorEvent: ActorEvent,
showEvent: ShowEvent
}>({
actorEvent: "actor-event",
showEvent: "show-event"
})

/** user-defined constants **/



/** user-defined types **/

export type Actor = { name: string; channel: WingChannelId; color: WingColor | null }
export type ActorEvent = { Added: [ActorId, Actor] } | { Removed: ActorId }
export type ActorId = number
export type Cue = { DcaAssignment: DcaAssignment }
export type DcaAssignment = { assignment: [(ActorId | null), (ActorId | null), (ActorId | null), (ActorId | null), (ActorId | null), (ActorId | null), (ActorId | null), (ActorId | null), (ActorId | null), (ActorId | null), (ActorId | null), (ActorId | null), (ActorId | null), (ActorId | null), (ActorId | null), (ActorId | null)] }
export type MixConfig = { actors: Partial<{ [key in ActorId]: Actor }> }
export type Show = { mixConfig: MixConfig; cues: Cue[] }
export type ShowEvent = { Loaded: Show }
export type WingChannelId = number
export type WingChannelInfo = { name: string; color: WingColor }
export type WingColor = "GrayBlue" | "MediumBlue" | "DarkBlue" | "Turquoise" | "Green" | "OliveGreen" | "Yellow" | "Orange" | "Red" | "Coral" | "Pink" | "Mauve"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
